# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(277, 170)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_Cancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cancelar.setGeometry(QtCore.QRect(140, 100, 71, 31))
        self.btn_Cancelar.setObjectName("btn_Cancelar")
        self.l_Nombre = QtWidgets.QLabel(self.centralwidget)
        self.l_Nombre.setGeometry(QtCore.QRect(40, 30, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.l_Nombre.setFont(font)
        self.l_Nombre.setObjectName("l_Nombre")
        self.l_Apellido = QtWidgets.QLabel(self.centralwidget)
        self.l_Apellido.setGeometry(QtCore.QRect(40, 60, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Apellido.sizePolicy().hasHeightForWidth())
        self.l_Apellido.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.l_Apellido.setFont(font)
        self.l_Apellido.setObjectName("l_Apellido")
        self.input_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.input_Nombre.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.input_Nombre.setObjectName("input_Nombre")
        self.Input_Apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.Input_Apellido.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.Input_Apellido.setObjectName("Input_Apellido")
        self.btn_Aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Aceptar.setGeometry(QtCore.QRect(60, 100, 71, 31))
        self.btn_Aceptar.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btn_Aceptar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btn_Aceptar.setAcceptDrops(False)
        self.btn_Aceptar.setCheckable(True)
        self.btn_Aceptar.setChecked(True)
        self.btn_Aceptar.setAutoDefault(False)
        self.btn_Aceptar.setObjectName("btn_Aceptar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Cancelar.setText(_translate("MainWindow", "Cancelar"))
        self.l_Nombre.setText(_translate("MainWindow", "Nombre"))
        self.l_Apellido.setText(_translate("MainWindow", "Apellido"))
        self.btn_Aceptar.setText(_translate("MainWindow", "Aceptar"))
